[provider]
cluster = "devnet"
wallet = "./deployer-keypair.json"

[programs.localnet]
seth_bridge = "5V3anofFhgpB9D8Uc72JDHg1VVH8qxJJrtaEMMxS4kmw"

[programs.devnet]
seth_bridge = "5V3anofFhgpB9D8Uc72JDHg1VVH8qxJJrtaEMMxS4kmw"

[scripts]
initialize = "node scripts/initialize.js"
test = "node scripts/test.js"

[[test.validator.account]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
filename = "./accounts/spl-token.json"