[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=453899d1-2296-4503-b3df-fcc3c64436bc"
wallet = "./deployer-keypair.json"

[workspace]
members = [".", "dirm"]

[programs.localnet]
seth_bridge = "2PpwtfR2QHfR7qGhH8eaeiTiJac8LfdSQFdR6FJf6aF9"
dirm = "idehdzFDKcnizix3YGrBs1T1JP5YFZaCrGeKJeuYZ62"

[programs.devnet]
seth_bridge = "GmfLWKJuTgyaNvro91Vd8mwg8BXccgXS3jZ4WTjsAan5"
dirm = "idehdzFDKcnizix3YGrBs1T1JP5YFZaCrGeKJeuYZ62"

[scripts]
initialize = "node scripts/initialize.js"
test = "node scripts/test.js"

[[test.validator.account]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
filename = "./accounts/spl-token.json"